apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: MTIzNA==  # 1234 en base64
  username: YWRtaW4=       # admin en base64
  password: MTIzNA==   # password en base64